#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sortenc1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  pos2,           sensorTouch)
#pragma config(Sensor, dgtl10, pos3,           sensorTouch)
#pragma config(Sensor, dgtl11, startsw,        sensorTouch)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           sortmotor,     tmotorVex393_MC29, openLoop, encoderPort, dgtl1)
#pragma config(Motor,  port3,           indexservo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[sortenc1] = 0;
	while(true){
		if(SensorValue[startsw]){
			if(SensorValue[sortenc1] < 0){
				repeatUntil(SensorValue[sortenc1] == 0){
					startMotor(sortmotor, -35);
				}
				stopMotor(sortmotor);
			}
			if(SensorValue[sortenc1] > 0){
				repeatUntil(SensorValue[sortenc1] == 0){
					startMotor(sortmotor, 35);
				}
				stopMotor(sortmotor);
			}
		}
		if(SensorValue[pos2]){
			if(SensorValue[sortenc1] < -250){
				repeatUntil(SensorValue[sortenc1] == -250){
					startMotor(sortmotor, -35);
				}
				stopMotor(sortmotor);
			}
			if(SensorValue[sortenc1] > -250){
				repeatUntil(SensorValue[sortenc1] == -250){
					startMotor(sortmotor, 35);
				}
				stopMotor(sortmotor);
			}
		}
		if(SensorValue[pos3]){
			if(SensorValue[sortenc1] < -565){
				repeatUntil(SensorValue[sortenc1] == -565){
					startMotor(sortmotor, -35);
				}
				stopMotor(sortmotor);
			}
			if(SensorValue[sortenc1] > -565){
				repeatUntil(SensorValue[sortenc1] == -565){
					startMotor(sortmotor, 35);
				}
				stopMotor(sortmotor);
			}
		}
	}
}
