#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  pos1,           sensorTouch)
#pragma config(Sensor, dgtl2,  pos2,           sensorTouch)
#pragma config(Sensor, dgtl3,  pos3,           sensorTouch)
#pragma config(Sensor, dgtl11, sortenc1,       sensorQuadEncoder)
#pragma config(Motor,  port1,           sortmotor,     tmotorVex393_HBridge, PIDControl, encoderPort, dgtl11)
#pragma config(Motor,  port2,           indexservo,    tmotorServoStandard, openLoop)
#pragma config(DatalogSeries, 0, "Encoder_Value", Sensors, Sensor, dgtl11, 50)
#pragma config(DatalogSeries, 1, "SortMotor_Pwr", Motors, MotorPower, port1, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[sortenc1] = 0;
	while(true){
		if(SensorValue[pos1]){
			if(SensorValue[sortenc1] < 1800){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, 100);
					//waitUntil(SensorValue[sortenc1] = 1800);
				}
				stopMotor(sortmotor);
			}
			if(SensorValue[sortenc1] > 1800){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, -100);
				}
				stopMotor(sortmotor);
			}
		}
		if(SensorValue[pos2]){
			if(SensorValue[sortenc1] < 600){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, 100);
				}
			}
			if(SensorValue[sortenc1] > 600){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, -100);
				}
			}
		}
		if(SensorValue[pos3]){
			if(SensorValue[sortenc1] < 1200){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, 100);
				}
			}
			if(SensorValue[sortenc1] > 1200){
				repeatUntil(SensorValue[sortenc1] == 1800){
					startMotor(sortmotor, -100);
				}
			}
		}
	}
}
