#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  startsw,        sensorTouch)
#pragma config(Sensor, dgtl11, sortenc1,       sensorQuadEncoder)
#pragma config(Motor,  port1,           sortmotor,     tmotorVex393_HBridge, PIDControl, encoderPort, dgtl11)
#pragma config(Motor,  port2,           indexservo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	SensorValue[sortenc1] = 0;
	while(SensorValue[sortenc1] < 1800){
startMotor(sortmotor, 100);
}
//while()
}
