#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sortenc1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl10, metalsw,        sensorTouch)
#pragma config(Sensor, dgtl11, startsw,        sensorTouch)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           sortmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           indexservo,    tmotorServoStandard, openLoop)
#pragma config(DatalogSeries, 0, "Encoder Pos", Sensors, Sensor, dgtl1, 50)
#pragma config(DatalogSeries, 1, "SortMtr Pwr", Motors, MotorPower, port2, 50)
#pragma config(DatalogSeries, 2, "LineFollw Val", Sensors, Sensor, in1, 50)
#pragma config(DatalogSeries, 3, "Metal SW", Sensors, Sensor, dgtl10, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Sort Motor Speed
int posmotor = 25;
int negmotor = -25;

//Servo Value Constants
int grabmarble = 40;
int dropmarble = -70;
int scanclosed = -100;
int neutral = 0;

//Encoder Position Values
int metalbox = 0;
int clearbox = 261;
int opaquebox = -219;

//Marble Line Follow Value Constants
int clearlo = 2196;
int clearhi = 2779;
//int woodlo = 317;
//int woodhi = 1128;
int opaquelo = 0;
int opaquehi = 1000;

task main()
{
	while(true){	//Strictly a failsafe in case the following loop is somehow exited

		//Setup - Run only once, starts immediately upon pressing "Start" in the RobotC environment
		setServo(indexservo, scanclosed);
		SensorValue[sortenc1] = 0;
		motor[light] = 127;

		if(SensorValue[startsw]){	//Once the start switch is pressed, enter the sort loop
			while(true){
				setServo(indexservo, grabmarble); //Grab the first marble
				wait(0.4);
				setServo(indexservo, dropmarble); //Drop the marble on the track to the sorter
				wait(0.4);
				setServo(indexservo, scanclosed); //Close the line follower all the way
				wait(4);

				//Begin Marble Type Determnination
				if(SensorValue[metalsw]){	//If the paperclips create a contact closure
					if(SensorValue[sortenc1] < metalbox){	//If the metal box is off to the left
						repeatUntil(SensorValue[sortenc1] == metalbox){	//move box to the center
							startMotor(sortmotor, negmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
					if(SensorValue[sortenc1] > metalbox){	//If the metal box is off to the right
						repeatUntil(SensorValue[sortenc1] == metalbox){	//move box to the center
							startMotor(sortmotor, posmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
				}
				if(SensorValue[linefollow] >= clearlo && SensorValue[linefollow] <= clearhi){
					//If the readout value from the light sensor is within the range applicable to clear marbles
					if(SensorValue[sortenc1] < clearbox){	//If the clear box is off to the right
						repeatUntil(SensorValue[sortenc1] == clearbox){	//move box to the center
							startMotor(sortmotor, negmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
					if(SensorValue[sortenc1] > clearbox){	//If the clear box is off to the right
						repeatUntil(SensorValue[sortenc1] == clearbox){	//move box to the center
							startMotor(sortmotor, posmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
				}
				if(SensorValue[linefollow] >= opaquelo && SensorValue[linefollow] <= opaquehi){
					//If the readout value from the light sensor is within the range applicable to clear marbles
					if(SensorValue[sortenc1] < opaquebox){	//If the opaque box is off to the left
						repeatUntil(SensorValue[sortenc1] == opaquebox){  //move box to the center
							startMotor(sortmotor, negmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
					if(SensorValue[sortenc1] > opaquebox){	//If the opaque box is off to the right
						repeatUntil(SensorValue[sortenc1] == opaquebox){  //move box to the center
							startMotor(sortmotor, posmotor);
						}
						stopMotor(sortmotor);
						setServo(indexservo, neutral);	//Drop the marble
					}
				}
			}
		}
	}
}
