#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sortenc1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl10, metalsw,        sensorTouch)
#pragma config(Sensor, dgtl11, startsw,        sensorTouch)
#pragma config(Motor,  port1,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           sortmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           indexservo,    tmotorServoStandard, openLoop)
#pragma config(DatalogSeries, 0, "Encoder Pos", Sensors, Sensor, dgtl1, 50)
#pragma config(DatalogSeries, 1, "SortMtr Pwr", Motors, MotorPower, port2, 50)
#pragma config(DatalogSeries, 2, "LineFollw Val", Sensors, Sensor, in1, 50)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		//	while(true){
		//		while(SensorValue[startsw]){
		//			setServo(indexservo, 90);
		//		}
		//		setServo(indexservo, -100);
		//setServo(indexservo, -70);
		//	}
		motor[light] = 127;
		setServo(indexservo, -100);
		SensorValue[sortenc1] = 0;
		if(SensorValue[metalsw]){
			while(true){
				setServo(indexservo, 90);
				wait(1);
				setServo(indexservo, -70);
				wait(0.5);
				setServo(indexservo, -100);
				wait(5);
			}
		}
	}
}
