#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    linefollow,     sensorLineFollower)
#pragma config(Sensor, dgtl1,  sortenc1,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, startsw,        sensorTouch)
#pragma config(Motor,  port1,           sortmotor,     tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           light,         tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port3,           indexservo,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(true){
		while(SensorValue[startsw]){
			setServo(indexservo, 90);
		}
		//setServo(indexservo, -100);
		setServo(indexservo, -80);
	}
}
